"""Add indexes

Revision ID: 1eb2693a04eb
Revises: 32401f6565ad
Create Date: 2015-10-01 15:38:02.063821

"""

# revision identifiers, used by Alembic.
revision = '1eb2693a04eb'
down_revision = '32401f6565ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_variable_experiment'), 'variable', ['experiment'], unique=False)
    op.create_index(op.f('ix_variable_mip'), 'variable', ['mip'], unique=False)
    op.create_index(op.f('ix_variable_model'), 'variable', ['model'], unique=False)
    op.create_index(op.f('ix_variable_variable'), 'variable', ['variable'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variable_variable'), table_name='variable')
    op.drop_index(op.f('ix_variable_model'), table_name='variable')
    op.drop_index(op.f('ix_variable_mip'), table_name='variable')
    op.drop_index(op.f('ix_variable_experiment'), table_name='variable')
    ### end Alembic commands ###
