"""Remove file table

Revision ID: 32401f6565ad
Revises: 2b79334818ff
Create Date: 2015-09-30 15:06:59.379765

"""

# revision identifiers, used by Alembic.
revision = '32401f6565ad'
down_revision = '2b79334818ff'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version_id', sa.INTEGER(), nullable=True),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('owner', sa.VARCHAR(), nullable=True),
    sa.Column('modified', sa.DATE(), nullable=True),
    sa.Column('start', sa.DATE(), nullable=True),
    sa.Column('end', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], [u'version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
