"""add tables

Revision ID: 355a156d4b58
Revises: 3bb692750328
Create Date: 2015-09-29 14:31:17.623543

"""

# revision identifiers, used by Alembic.
revision = '355a156d4b58'
down_revision = '3bb692750328'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.String(), nullable=True),
    sa.Column('experiment', sa.String(), nullable=True),
    sa.Column('mip', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('ensemble', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('modified', sa.Date(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('version')
    op.drop_table('variable')
    ### end Alembic commands ###
