"""initial

Revision ID: 3bb692750328
Revises: 
Create Date: 2015-09-29 14:27:57.656945

"""

# revision identifiers, used by Alembic.
revision = '3bb692750328'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
