package:
    name: arccssive
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    string: {{ GIT_BUILD_STR }}

source:
    git_url: ../

build:
    script: python setup.py install
    script_env:
        - ARCCSSIVE_DB
        - ARCCSSIVE_USER

requirements:
    build:
        - python
        - pbr
    run:
        - python
        - six
        - sqlalchemy
        - esgf-pyclient
        - psycopg2
        - requests

test:
    source_files:
        - setup.cfg
        - conftest.py
        - tests
    requires:
        - pytest
    commands:
        - py.test

about:
    home: https://github.com/coecms/ARCCSSive
    license: Apache 2.0
    license_file: LICENSE
    summary: ARCCSS Data Archive Tools
