REFRESH MATERIALIZED VIEW cf_variable_link;
REFRESH MATERIALIZED VIEW cmip5_attributes_raw;
REFRESH MATERIALIZED VIEW cmip5_attributes_links;
REFRESH MATERIALIZED VIEW cmip5_dataset;
REFRESH MATERIALIZED VIEW cmip5_file_version;
REFRESH MATERIALIZED VIEW old_cmip5_instance;
REFRESH MATERIALIZED VIEW old_cmip5_version_raw;
REFRESH MATERIALIZED VIEW cmip5_path;
